FROM eclipse-temurin:21

WORKDIR /build

COPY --chmod=0755 mvnw mvnw
COPY .mvn/ .mvn/
COPY pom.xml pom.xml
COPY ./src src/

RUN ./mvnw package -DskipTests

EXPOSE 7070

ENTRYPOINT [ "java", "-jar", "target/app-shaded.jar" ]